### ISSUE TITLE
vue deleteData callback

### ISSUE THREAD

**Issue by luckysei** [nhn/tui.grid#1066]
**Summary**
Can I control success or failure when deleting grid data using deleteData property?

I don't know how to apply grid.on callback function in vue.

As far as I know, the onGridUpdated property does not work with deleteData.

**Screenshots**
We're currently using a function called as shown in the picture.

If applicable, add screenshots to help explain your question.
![image](https://user-images.githubusercontent.com/62042518/82854628-faf1d780-9f43-11ea-9478-67a745066f7c.png)

**Version**
"@toast-ui/vue-grid": "^4.12.1"

**Additional context**
It doesn't work, but it has the overall source on it.
https://jsfiddle.net/gmps03h5/

This article was written through a translator.

**Comment by js87zz** [comment]
@luckysei 
Currently, the grid is not updated when send the request like `delete`, `create` and `update`. Because the request is sent at once with the data which is already changed through API like `removeCheckedRows`.
I think that [successResponse](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-event.md) event will be helpful to you as below.
```js
<Grid @successResponse="..." />
```
