### ISSUE TITLE
beforeFilter event not working

### ISSUE THREAD

**Issue by denaldhushi** [nhn/tui.grid#1067]
Hello,

I am trying to use the new event **beforeFilter** on grid but nothing is happening before I execute a filter. 
```
beforeFilter: (ev) => {
     //code here
},
```
I have used this in the body of grid, also into column headers.

Thanks!

> **Note**: Library is updated to v4.13.0

**Comment by js87zz** [comment]
@denaldhushi 
Can you give more detail source code for configuring the grid?
You configure the event as below?
```js
const grid = new Grid({
  data,
  columns,
  // ...
});

grid.on('beforeFilter', (ev) => {
  // ...
});
```

**Comment by js87zz** [comment]
@denaldhushi 
Sorry for late replying.
when I tested it, the event has been triggered properly. 
Can you give me your example source code in jsfiddle or code sandbox?

**Comment by denaldhushi** [comment]
[here](https://codesandbox.io/s/tui-grid-example-git-cwrtb) is a part of the source code.
Can you check it please if something is wrong ? And can you give me an example how to use the event `beforeFilter` ?

Thanks

**Comment by js87zz** [comment]
@denaldhushi 
The functionality of filter is not operated with dataSource yet, So that we need to develop this part further. It seems to be not problem to trigger `beforeFilter` event in your source code, but there will be problem on pagination with dataSource.(*I don't know exactly why the event doesn't occur, because your example code doesn't work in sandbox.*) 
I think that it's better to use the filter operation with dataSource after we develop the feature.

There are thhe purpose and example code about `beforeFilter` in [here](https://github.com/nhn/tui.grid/issues/1042)
