### ISSUE TITLE
Pagination layout

### ISSUE THREAD

**Issue by denaldhushi** [nhn/tui.grid#1068]
Hello, 

Is possible to move the **pagination** on top of the table ? 

Thanks

**Comment by js87zz** [comment]
@denaldhushi 
We have the [PR](https://github.com/nhn/tui.grid/pull/950) for the option you commented. However, it has been not merged because we should consider more thing internally.

**Comment by denaldhushi** [comment]
yes, I see that, but it is tied to the grid, like the footer one is now, I would like to have the pagination as a separate component that I can put wherever I need to, because I don't want it just on top.
I want to be able to put buttons in front and other elements behind it.
I want to be able to put it wherever we need to.

**Comment by js87zz** [comment]
@denaldhushi 
We have a plan to add the option for the position(only `top`, `bottom`) of pagination component.
The flexible change in the position of it does not seem to be an option which the grid should provide. I think that it is the rare case and separate use of pagination component from the grid seems suitable for usability.

**Comment by joebordes** [comment]
I don't agree with that because I think the grid pagination is "just" another of the many actionable elements a grid may have. For example, I personally need to be able to put buttons and a message above the grid and I would like to have all those together with the pagination element (inside the same header div).

Besides, if someone needs to put the pagination somewhere else, with some other design (vertical stack for example), why should the grid mandate how those buttons should be?  The grid should be good at what the grid does, and the pagination should be good at what it does.

**Comment by js87zz** [comment]
@joebordes 
Grid can control the pagination component internally to manipulate DOM or sync the state of pagination. But if the pagination component attach to specific position(wherever user want), It is hard to control the pagination component. If the user want it, I think it's right to create pagination where you want it to be separately and user should control the pagination component directly to operated with grid directly.

**Comment by js87zz** [comment]
@denaldhushi 
The `pageOptions.position` option is added in `v4.14.0`. You can use the option as below.
```js
 const grid = new Grid({
   data,
   columns,
   // ...
   pageOptions: {
     // ...
     // move the pagination component on top
     position: 'top'
   }
 })
```
Thank you!
