### ISSUE TITLE
will be re-rendered when the grid scrolls.

### ISSUE THREAD

**Issue by jochouen** [nhn/tui.grid#1127]
**Summary**
In using '@toast-ui/react-grid' in TypeScript.
will be re-rendered when the grid scrolls.
This looks like a bug.
Is it a problem with my code or is it really a bug?

**Screenshots**
![test](https://user-images.githubusercontent.com/10725284/88024258-62578c80-cb6d-11ea-954f-0a8f0bd406be.gif)

**Version**
@toast-ui/react-grid
4.12.1

**Additional context**
this is sample code.
```
import ....
.......

class SampleContent {
  private el: HTMLDivElement;

  constructor(props: CellRendererProps) {
    console.log('constructor!!!!!!!!!!!!!!!!!!!!!');
    const rootDom = document.createElement('div');
    this.el = rootDom;
    this.render(props);
  }

  getElement() {
    return this.el;
  }

  render(props: CellRendererProps) {
    console.log('render!!!!!!!!!!!!!!!!!!!!!');
    const element = <span>test</span>;
    ReactDOM.render(element, this.el);
  }
}

const GridSample: React.FC = () => {
  const columns = [
    {name: 'id', header: 'ID', renderer: SampleContent},
    {name: 'name', header: 'Name'}
  ];

  const data = [
    {
     ...
    }
  ];

  return <Grid
          columns={columns}
          data={data}
          columnOptions={{
            frozenCount: 1,
            frozenBorderWidth: 2,
            minWidth: 100
          }}
          bodyHeight={150}
          scrollY
        />
};

....
```

**Comment by js87zz** [comment]
@jochouen 
It's not the bug.
The cells of grid are only rendered within the **range of the viewport** which is calculated using the scroll, offset position.
In other words, all cells are not rendered on the grid at once. The rendered cells are changed as range of the viewport.
If you move the scroll position vertically, the cells are newly rendered because range of the viewport is changed.
In general, this is called `virtual scrolling`.

**Comment by jochouen** [comment]
@js87zz 
I got it,  thanks for your answer.
