### ISSUE TITLE
그리드 columns 속성 name에 관련되서 질문이 있습니다.

### ISSUE THREAD

**Issue by nikJ6034** [nhn/tui.grid#1268]
제가 지금 vue를 사용하면서 toast 그리드를 사용하고 있는데요

불편한점이 하나 있어서 문의드려요.

restApi에서 오브젝트를 {test:'test1'}
이렇게 들어오면 columns 에 {header: '테스트', name:'test'} 셋팅해서 사용할 수 있는데요
만약

{parents:{test:'test'}}

이렇게 들어왔을때 {header: '테스트', name:'parents.test'} 이렇게는 사용이 안되더라고요.

그래서 다시 데이터를 재 가공해서 사용하는데 좀 불편해서 기능이 있는지, 없으면 추가해주실 수 있는지 궁금합니다.

참고로 bootstrap-vue에 table 컴포넌트는 위와 같이 사용이 가능해요 그래서 편리하더라고요. ㅎㅎ

**Comment by js87zz** [comment]
@nikJ6034 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

There is no specific plan to handle option for data processing yet. Perhaps if there is a plan, it will be later because there are other priority features.
