### ISSUE TITLE
Send dynamic paramters with readData API

### ISSUE THREAD

**Issue by denaldhushi** [nhn/tui.grid#1316]
Hi there, 

I am trying to send parameters with dynamic value, but it send always the same value.
```js
api: {
	readData: {
		url: url,
		method: 'GET',
		initParams: {
			lastPage: lastPage
		}
	}
},
```
`lastPage` variable is going always 1 for example, but it should change for every request. 
Is any way that I can do it working correct ? 

Thanks

**Comment by js87zz** [comment]
@denaldhushi 
If you don't update directly to the new value, the value will be not changed. However, this seems to be a problem, as it should only be sent on initial request. I'll check it out!

**Comment by denaldhushi** [comment]
@js87zz thank you! if you can please check it as soon as possible!

**Comment by denaldhushi** [comment]
hi @js87zz ,

Do you have any update for that issue, please ?

Thanks

**Comment by js87zz** [comment]
@denaldhushi 
It will be fixed the next bugfix release. Thanks!

**Comment by denaldhushi** [comment]
@js87zz

**Comment by js87zz** [comment]
@denaldhushi 
I've forgotten this issue because I was busy with other things.. I'm so sorry for the late response.🙏

I think you want to update `lastPage` when moving the page, is that right? If so, I think you can do it as below. 
```js
grid.on('beforePageMove', (ev) => {
  ev.stop();

  const { page } = ev;
  grid.readData(page, { lastPage: page });
});
```
If not, I'd appreciate it if you could explain your scenario. 

I'm sorry again for the late response.
