### ISSUE TITLE
Lazy Observable 관해서 질문이 있습니다.

### ISSUE THREAD

**Issue by zerothree3782** [nhn/tui.grid#1540]
안녕하세요. 
좋은 프로그램을 개발 해주신덕분에 잘 사용하고 있습니다. 
다름이 아니라 제가 grid사용 하면서 10만개의 데이터를 추가 하면 렌더링시 약 5초의 시간이 걸리던데
https://ui.toast.com/weekly-pick/ko_20191204 개발자 분께서 작성하신 글을 읽어보니 Lazy Observable적용으로
렌더링시간이 확 줄었다고 하는데 혹시 4.2버전에서는 적용이 되어있지 않은건가요???
아니면 Lazy Observable을 사용하기 위해서 따로 설정해줘야하는 부분이 있는건가요?
감사합니다.

**Comment by jajugoguma** [comment]
@zerothree3782 
Please make sure you have filled out issue respecting our form in English and given us as much context as possible. If not, the issue will be closed or not replied.

Lazy obervable has been applied since version 4.2.0 and does not require any configuration.
Can you provide example code for the problem you are experiencing through codesandbox, etc.?
