### ISSUE TITLE
Questions about how to apply grid edition theme when using custom renderer.

### ISSUE THREAD

**Issue by HyunJ1k** [nhn/tui.grid#1552]
Hi.

I'd like to ask you about the use of toast grids.
We used the custom renderer function to use the regular html check box.

    class CustomCheckBox {
        constructor(props) {
            const el = document.createElement("input");
            const { grid, rowKey, columnInfo } = props;

            el.type = "checkbox";
            el.checked = props.value == "Y" ? true : false;

            el.onchange = function (e) {
                grid.setValue(rowKey, columnInfo.name, this.checked ? "Y" : "N");
            };

            this.el = el;
            this.render(props);
        }

      .....
    }

    option = {
        renderer: {
            type: CustomCheckBox,
        }
    };

It is used in this way, and the edit attribute of the theme you set is excluded even though the edit function (checkbox) is in use.
Is there a way to add style even if you use a custom renderer?

     tui.Grid.applyTheme('default', {
                cell: {
                    editable: {
                        background: '#ddeeff'
                    }
                }
            });

![image](https://user-images.githubusercontent.com/49899570/149475062-23307b34-4643-4149-b9f5-0f49a009943b.png)

ps.[[link](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md#%EB%94%94%ED%8F%B4%ED%8A%B8-%EB%A0%8C%EB%8D%94%EB%9F%AC-%EC%8A%A4%ED%83%80%EC%9D%BC%EB%A7%81)] - 
Unfortunately, the functionality of the link was not duplicated.

Thank.

**Comment by jajugoguma** [comment]
@chohyunjik2 
The theme is not applied because the column is not editable.
Also, the style of the custom renderer should be applied from inside, like [this code](https://github.com/nhn/tui.grid/blob/13947c15ff66737027a62f6df131b51c05aff5d9/packages/toast-ui.grid/src/renderer/default.ts#L35).

There is two ways to apply theme to the column with checkbox.
First, change the column to be editable.
Or, add a `'tui-grid-cell-editable'` class to the column.

Thanks!
