### ISSUE TITLE
onClick being stripped out of HTML of JSON in release 4.21.3

### ISSUE THREAD

**Issue by ymc-stewart-ridgway** [nhn/tui.grid#1744]
**Describe the bug**
Prior to version 4.21.3 it was possible to have onClick event in HTML of JSON string value. Since version 4.21.3 the onClick is being stripped out.

**To Reproduce**
1. Send JSON to grid via API (gridInstance.data.api.readData.url)
2. Have a column with value of something like "<a onclick='alert(1);'>One</a>"
3. Inspect cell and observe that onclick is stripped out with version 4.21.3
4. Repeat with Grid version 4.21.2, and observe that the onclick is intact and working

**Expected behavior**
Onclick should be preserved, or breaking changes announced if this is intentional.

**Comment by 10sa** [comment]
It is intented behavior. since 4.21.2, values are filtered by `dompurify` (https://github.com/nhn/tui.grid/pull/1741/commits/b3d00c1e4ae4b0cc05bd3fd6bc5b576368e9c3fb). this is a fix of XSS vulnerability. (https://github.com/nhn/tui.grid/issues/1669)

However, readData feature is designed for data reading, not a script appending. i think it is unintended usage.

If you want cell click event, how about use [grid events](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/en/custom-event.md#gridevent) ? it can receive cell clicking event.
