### ISSUE TITLE
pagination event , afterMove / beforeMove not work in grid

### ISSUE THREAD

**Issue by BoABae** [nhn/tui.grid#801]
**Summary**
pagination event , afterMove / beforeMove not work in grid

**Screenshots**
<img width="828" alt="스크린샷 2019-11-15 오후 3 25 57" src="https://user-images.githubusercontent.com/21331221/68921487-4ae52a00-07bc-11ea-8278-969ed2c84ebd.png">

        var pagination = this._grid.getPagination();

        pagination.reset(count);

        pagination.on('beforeMove', function(ev) {
          var page = ev.page;
          console.log(page);
        });

**Version**
tui.grid 4.5.2
tui.pagination 3.3.3

**Additional context**
When Grid initialized, after call data( 5 row append ) and then
getting instance pagination, pagination reset page total count. ( No data on all pages except first page grid )

I expected 'beforeMove' event when I move to page two, but the error is like this.

**Comment by js87zz** [comment]
@BoABae 
The event callback is executed, but parameter is not valid as the result. This need to be fixed.
We don't recommend that change the pagination count like `pagination.reset(count);` because this causes side effect. Try to change the pagination count through configuring `pageOptions` options or `resetData` API.
