### ISSUE TITLE
inquiry about tui-Grid pagination totalCount 

### ISSUE THREAD

**Issue by gurgus0189** [nhn/tui.grid#851]
## Version
 4.6.0

## Development Environment
crome

## Current Behavior

```js
// Write example code
```

## Expected Behavior

In the case of tui-grid pagination, it seems to be how to get TotalCount to compose the page.

ex) If there are 1000 data in total and 10 data are displayed in one page
     Generate 1 to 100 pages

In the example above, the totalcount is taken and the page is composed, so the more data you have, the longer the loading time will be.
I don't want to get the TotalCount, but I need to click the Next button to get the next page (ie how to display the data on the next page only when the user clicks the Next button). )
Do you support tui-Gird?
And if there is a large amount of data, if I get TotalCount and page it, will there be a speed effect?

**Comment by js87zz** [comment]
@gurgus0189 
Please respect our policy that writing the form **in English** to share our issue to other people.
Change the title and content in English. 
It's helpful to give us detail example source to comprehend your question.

**Comment by js87zz** [comment]
@gurgus0189 
1. We already offer pagination functionality get page data when moves the page through [dataSource](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/data-source.md) option. 
2. The performance of large data is very fast so that your case will be no problem.
Refer this [example](https://nhn.github.io/tui.grid/latest/tutorial-example25-large-data-performance). The example has 10,0000 rows and 10 columns, but grid is rendered very quickly.

**Comment by gurgus0189** [comment]
As you answered, even if you get 10,000 data, it renders very fast.
But every time I ask for 10,000 pieces of data or the total number of pieces of data, I think the server will be under load.

**Comment by js87zz** [comment]
@gurgus0189 
You can get the `sliced data` per page and `totalCount` through communicating with server. 
```js
const grid = new tui.Grid({
  el: document.getElementById('grid'),
  data: {
    api: {
      readData: { url: '/api/readData', method: 'GET' }
    }
  },
  pageOptions: {
    perPage: 5
  },
  columns: [
    {
      header: 'Name',
      name: 'name'
    },
    {
      header: 'Artist',
      name: 'artist'
    }
  ]
});
```
So you don't need to request all 800,000 data, because only sliced data is sent in that page and `totalCount` is only count for your data by executing `count` query. If the executing `count` query is slow to get `800,000` data, I think the problem would be about DB scheme indexing or sql performance.
