### ISSUE TITLE
Result of "getModifiedRows" is not include rows updated by key commands

### ISSUE THREAD

**Issue by leesum-in** [nhn/tui.grid#859]
**Describe the bug**
When delete any cell data with key commands('back space', 'del'), this row is not included in `getModifiedRows` result.

And also, `onAfterChange` is not triggered

**To Reproduce**
1. Press 'del' key on a cell with data.
2. Execute `grid.getModifiedRows`.
3. The result of execution is `{createdRows:[], updatedRows: [], deletedRows[]}`.

**Expected behavior**
Should be included in 'updatedRows'.

**Screenshots**
![image](https://user-images.githubusercontent.com/7876134/72056127-5c0b6c80-330f-11ea-8cca-3070e60a4232.png)

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser chrome
 - Version 4.8.1

**Comment by js87zz** [comment]
@ssucom502 
The value of the cell can be changed or deleted by keyMap operation or copy&paste currently.
But the custom event is not occurred due to the below case.

![스크린샷 2020-01-14 오후 12 52 55](https://user-images.githubusercontent.com/37766175/72312868-d0a62880-36cc-11ea-83be-b8063475f214.png)

If the cells of selection layer are deleted by pressing the `del` key, `onAfterChange` event will be fired as much as the count of changed cell in specific column. It's very inefficient and annoying. 
So we consider the another custom event to solve this issue. If the custom event about it is added and included in release, I will comment here. Thank you for your contributing! :)

**Comment by js87zz** [comment]
@leesum-in 
Sorry for late notice. 
This bug has been fixed in `v4.10.1`. 
However, current grid version is `v4.14.0`, so we recommend to use the latest version(`v4.14.0`). 
Thank you!
