### ISSUE TITLE
appendRow and click event questions

### ISSUE THREAD

**Issue by cwkang89** [nhn/tui.grid#872]
1. appendRow
I want to do appendRow continuously.
However, the rowKey value was not added after the appendRow run.
The following code does not appendRow to the desired location.
```js
focusChange ({rowKey}) {
  this.$refs.grid.invoke("appendRow", {}, { at: rowKey + 1 });
}
```

2. click
I want to give an event only when I click the plus icon in the picture below.
Currently, it is a grid focusChange event, but there is no response when you click the icon and it runs when click the cell.
The code below is the plus icon code.
  ```js
  {
    header: "Add / Delete",
    name: "col0",
    width: 100,
    formatter:() =>
     '<button
       type="button"
       class="btn btn-sm text-primary ml-1"
     >
       <i class="fas fa-plus fa-smm"
     </button>',
    align: "center"
},
```
**Version**
"@toast-ui/vue-grid": "^4.8.1"

<img width="1385" alt="스크린샷 2020-01-17 오후 5 24 53" src="https://user-images.githubusercontent.com/50858429/72596762-c3e53700-394f-11ea-815c-cfd0dbee2ea9.png">

**Comment by js87zz** [comment]
@cwkang89 
1. Do you want to append the row when focus cell is changed?
The `at` property of `options` in `appendRow` API parameter **is not always matched** to `rowKey`. `at` property **is same as** `row index`, refer this [API](https://nhn.github.io/tui.grid/latest/Grid#appendRow)
```js
grid.on('focusChange', ({ rowKey }) => {
  const index = grid.getIndexOfRow(rowKey);
  grid.appendRow({}, { at: index + 1 })
});
```

2. I think there is a problem that `focusChange` event is not triggered on clicking same cell because focused cell is not changed.
In your case, [custom renderer](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md) is exactly what you need.

**Comment by cwkang89** [comment]
@js87zz  thank you~!
Can I use custom render as component in vue?

**Comment by js87zz** [comment]
@cwkang89 
Yes. You can use the custom renderer in `Vue`. However, the format should be our defined option format(**pure javascript class**) **not vue component**.
