### ISSUE TITLE
 How do I put an image in a grid?

### ISSUE THREAD

**Issue by JunChoi-KR** [nhn/tui.grid#893]
Hello.
I saw that I used html to insert an image into the grid on the TOAST UI site.
So I tried to develop with reference to the API, but I can't find the code.
Can you see example code?

안녕하세요.
TOAST UI 사이트에서 html을 활용해 그리드에 이미지를 넣은 것을 보았습니다.
이에 따라 API를 참고해 개발하려 했으나 코드를 찾을 수 없습니다.
혹시 예시 코드를 볼 수 있을까요?

**Comment by js87zz** [comment]
@JunChoi-KR 
[custom renderer](https://github.com/nhn/tui.grid/blob/master/packages/toast-ui.grid/docs/ko/custom-renderer.md) will be helpful to you. 
There is an example code.
```js
class CustomRenderer {
  constructor(props) {
    const el = document.createElement('img');
    el.src = 'some-image-link';

    this.el = el;
    this.render(props);
  }

  getElement() {
    return this.el;
  }

  render(props) {
    // you can change the image link as changes the `value`
    this.el.src = String(props.value);
  }
}

const grid = new Grid({
  // ... another options
  columns: [
    {
      header: 'Custom',
      name: 'custom',

      // you can use like below in `v4.9.0`
      renderer: CustomRenderer,

      // or regardless of version
      renderer: {
        type: CustomRenderer,
        // define your option to need to be passed
        options: {}
      }
    },
    // ...
  ]
});
```
Our API: https://nhn.github.io/tui.grid/latest/
Our Document: https://github.com/nhn/tui.grid/tree/master/packages/toast-ui.grid/docs/ko

**Comment by bacloud22** [comment]
hi @js87zz 
thank you so much for the example, I think it is partially working but something is missing for me, or I don't understand how the custom renderer works.

![image](https://github.com/nhn/tui.grid/assets/130276583/12d724be-5bc9-4ad8-8e48-4fd953211e19)

As you can see there are two columns, the first is what I have, the second is what I want to achieve (rather than the value link, I want to render the img element)

the result with the custom renderer (the example), does not add the img element, it is there at runtime as you can see in console, but not being added to the table :/ 

I appreciate any of your help ^^

**Comment by bacloud22** [comment]
ofc the same code as yours 👍 

```js
class CustomImgRenderer {
    constructor(props) {
        const el = document.createElement('img')
        el.src = String(props.value)
        this.el = el
        this.render(props)
    }

    getElement() {
        return this.el
    }

    render(props) {
        // you can change the image link as changes the `value`
        this.el.src = String(props.value)
    }
}

```
