### ISSUE TITLE
Select all checkbox bug in infinite scroll

### ISSUE THREAD

**Issue by ryum91** [nhn/tui.grid#937]
**Describe the bug**
Select all checkbox bug in infinite scroll

**To Reproduce**
1. enable infinite scroll
2. load a lot of data
3. `Select All` click
4. scroll down
5. `Select All` is checked but added row is not checked

**Expected behavior**
added row is checked
but If you uncheck only a few rows after a `Select All`, you should consider behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/18422353/75636178-e7deac80-5c5f-11ea-824c-318d6f40333f.png)

**Desktop (please complete the following information):**
none

**Smartphone (please complete the following information):**
none

**Comment by js87zz** [comment]
The bug has been fixed in `v4.10.1`(#964).

**Comment by ryum91** [comment]
@js87zz 
The same problem occurs in version 4.10.1.
Please confirm.

**Comment by js87zz** [comment]
@ryum91 
The bug has been fixed in our test and example.
Could you get me grid configuration or exampled code?
![2020-03-23 16-17-51 2020-03-23 16_18_08](https://user-images.githubusercontent.com/37766175/77291645-077a6980-6d22-11ea-848b-e21d29021df1.gif)

**Comment by ryum91** [comment]
Please refer to codepen.
https://codepen.io/ryum/pen/rNVZZMJ?editors=0010

**Comment by js87zz** [comment]
@ryum91 
`client` type is problem. we will fix it in next bug fix release.
Thank you!

**Comment by js87zz** [comment]
@ryum91 
I considered this functionality with checkbox again deeply and discussed about it with my team.
To begin with conclusion, The header checkbox will be released and the `checked` states of added data will be not `checked` in case of adding data through infinite scroll.

The only displayed(paginated) data is affected by `checkAll` functionality because infinite scroll is regarded as a kind of pagination. 
The another problem is that data has already `_attributes.checked` value like as below.
```js
data = [
  // ...
  { a: 1, b: 2, c: 3, _attributes: { checked: true }},
  { a: 3, b: 4, c: 6, _attributes: { checked: false } }
]
```
If checking all `checked` states of added data is default operation with infinite scroll, it will cause conflict of priority in above case.
For these reasons and the uniformity with other functionality(`appendRow`, `setRow`..), we decided to not change `checked` state of added data through infinite scroll.(applying it to other API(`appendRow`, `setRow`..).

If you want check the all data like you commented, you can implement as an alternative like below.
([checkAll API](https://nhn.github.io/tui.grid/latest/Grid#checkAll), [scrollEnd event](https://nhn.github.io/tui.grid/latest/Grid#event-scrollEnd))
```js
grid.on('scrollEnd', () => { grid.checkAll(); })
```
Currently, header checkbox is not reacted properly with added data through infinite scroll or other API and it will be fixed in next release.
You have an another opinion, freely comment here. Thank you! :)

**Comment by ryum91** [comment]
(영어로는 내용 전달에 어려움이 있어서, 한글로 작성합니다...양해 부탁드립니다 ㅠㅠ)

답변 감사합니다.
충분히 많은 고민의 흔적이 보여지네요.

하지만 사용자 입장에선 다소 혼란스러울 수 있을 것 같긴 합니다.
사용자는 무한 스크롤의 개념과, 활성화 여부에는 관심이 없고 단순히 전체 체크를 할 뿐이니까요.
(예를 들어 전체 체크 후, 일부 Row 만 체크 해제하여 작업하는 경우)

예전에 무한 스크롤 기능을 가진 Grid를 만든 경험이 있는데
그때는 전체 체크에 대한 상태를 별도로 관리 하였습니다. (전체 체크 박스의 체크 여부와 상관 없는)

|사용자 행위|전체 체크 박스의 체크 여부|별도의 전체 체크 상태|
|---|---|---|
|init|false|false|
|checkAll|true|true|
|일부 Row uncheck|false|true|
|다시 checkAll|true|true|
|uncheckAll|false|false|

이처럼 별도의 전체 체크 상태는 "checkAll", "uncheckAll" 을 통해서만 제어하도록 하였으며,
새로 추가되는 Row의 check 상태 또한 별도의 전체 체크 상태를 통해 결정되게 하였습니다.

(번외로, 전체 체크 상태가 false인 경우, check된 row 계산시, 계산 횟수를 줄이기 위해 unchecked 된 row를 이용하여 계산하였습니다.)

일단 현재 tui-grid 기준에서는 말씀하신 내용이 팀에서 결정한 최선의 방법이라 생각하며,
제가 작성한 내용은 추후에 다시 의논해주시면 감사하겠습니다.

감사합니다.^^
